### ISSUE TITLE
Unmapped TCIA imaging_study descriptions/modalities

### ISSUE THREAD

**Issue by cgmeyer** [MIDRC/midrc_dicom_harmonization#8]
I've added a table of the unmapped imaging_study descriptions/modalities found in the MIDRC TCIA collections along with their frequency of occurrence.  Of the 9610 imaging studies across the TCIA datasets, only 54 imaging studies were unmapped with only 24 unique combinations of modality/description.
https://github.com/MIDRC/midrc_dicom_harmonization/pull/7

**Comment by fedorov** [comment]
Resolved by merging #7 (back in Nov 2022).
